server:
  port: 8081

spring:
  cloud:
    azure:
      # --- Key Vault como PropertySource (lee secretos al arrancar) ---
      keyvault:
        secret:
          property-sources:
            - name: swaply-key
              endpoint: https://swaply-key.vault.azure.net/

      # --- Cosmos con clave (NO AAD) ---
      cosmos:
        connection-mode: GATEWAY     # HTTPS/443, útil con firewalls
        endpoint: https://swaply-db.documents.azure.com:443/
        key: ${cosmos-readwrite-key} # <-- secreto en Key Vault
        database: swaplydb           # Asegúrate que coincide con el nombre real
        populate-query-metrics: true

